### PR TITLE
Add js hw wk6d1-2

### PR DESCRIPTION
**Pull request by lyntco**
Adding js work!

### CODE REVIEW

**Comment by lyntco** [comment]
smell me ! i smell like tomato pie.

**Comment by lyntco** [comment]
... There's no place safe for computers anymore

**Comment by epoch** [comment]
It's perfectly ok to smell like a tomato pie but you committed changes to other student's folders. That's a real problem

**Comment by lyntco** [comment]
That's what I told you the other day DT! I was trying to save you a headache later!

**Pull request closed without merging**
